theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: false
  blocks:
    key_figures:
      animated: false
  image_sizes:
    design_system:
      lightbox:
        disabled: true